import '../style.css';
// import { Catalog } from './catalog';
const wrapper = document.querySelector('.wrapper');
const aside:any = document.querySelector('.aside');

const Element = () => {
    const main = document.createElement('main');
    const catalogElement = document.createElement('div');
    const sneakersName = document.createElement('div');
    const basketPriceWrapper = document.createElement('div');
    const basket = document.createElement('div');
    const title = document.createElement('div');
    const basketElement = document.createElement('div');
    const basketItemInfoWrapper = document.createElement('div');
    const basketSneakersName = document.createElement('div');
    const plusWrapper = document.createElement('div');
    const promo = document.createElement('div');
    const promoTitle = document.createElement('div');
    const sneakersImage = document.createElement('img');
    const whiteBasket = document.createElement('img');
    const basketElementImage = document.createElement('img');
    const deleteBasketItem = document.createElement('img');
    const price = document.createElement('span');
    const minus = document.createElement('span');
    const quantity = document.createElement('span');
    const plus = document.createElement('span');
    const basketPrice = document.createElement('span');
    const inputWrapper = document.createElement('div');
    const promoInput = document.createElement('input');
    const promoButton = document.createElement('button');
    const total = document.createElement('div');
    const totalTitlesWrapper = document.createElement('div');
    const subtotal = document.createElement('span');
    const tax = document.createElement('span');
    const shipping = document.createElement('span');
    const totalTitle = document.createElement('span');
    const totalPricesWrapper = document.createElement('div');
    const subtotalPrice = document.createElement('span');
    const taxPrice = document.createElement('span');
    const shippingPrice = document.createElement('span');
    const totalTitlePrice = document.createElement('span');

    sneakersImage.alt="vintage brights sneakers";
    sneakersImage.src="src/img/vintage.png";
    whiteBasket.src="src/icons/white-basket.svg";
    basketElementImage.src="src/img/vintage.png";
    deleteBasketItem.src="src/icons/delete.svg";
    promoInput.placeholder="Placeholder Text";

    basketSneakersName.innerHTML = 'New Balance 574 Vintage<br>Brights';
    price.innerText = '$ 650';
    title.innerText = 'My basket';
    sneakersName.innerText = 'New Balance 574 Vintage Brights';
    minus.innerText = '-';
    quantity.innerText = '1';
    plus.innerText = '+';
    basketPrice.innerText = '$ 650';
    promoTitle.innerText = 'Promo code';
    promoButton.innerText = 'Apply';
    subtotal.innerText = 'Subtotal';
    tax.innerText = 'Tax';
    shipping.innerText = 'Shipping';
    totalTitle.innerText = 'Total';
    subtotalPrice.innerText = '$ 1 850';
    taxPrice.innerText = '$ 100';
    shippingPrice.innerText = '$ 150';
    totalTitlePrice.innerText = '$ 2 100';

    main.classList.add('catalog');
    catalogElement.classList.add('catalog-element');
    sneakersImage.classList.add('sneakers-image');
    sneakersName.classList.add('sneakers-name');
    basketPriceWrapper.classList.add('basket-price-wrapper');
    whiteBasket.classList.add('white-basket');
    price.classList.add('price');
    basket.classList.add('basket');
    title.classList.add('title');
    basketElement.classList.add('basket-element');
    basketItemInfoWrapper.classList.add('basket-item-info-wrapper');
    basketSneakersName.classList.add('basket-sneakers-name');
    plusWrapper.classList.add('plus-wrapper');
    minus.classList.add('minus');
    quantity.classList.add('quantity');
    plus.classList.add('plus');
    basketPrice.classList.add('price');
    deleteBasketItem.classList.add('delete-basket-item');
    basketElementImage.classList.add('basket-element-image');
    promo.classList.add('promo');
    promoTitle.classList.add('promo-title');
    promoInput.classList.add('promo-input');
    promoButton.classList.add('promo-button');
    total.classList.add('total');
    totalTitlesWrapper.classList.add('total-titles-wrapper');
    subtotal.classList.add('subtotal');
    tax.classList.add('tax');
    shipping.classList.add('shipping');
    totalTitle.classList.add('total-title');
    totalPricesWrapper.classList.add('total-prices-wrapper');
    subtotalPrice.classList.add('subtotal-price');
    taxPrice.classList.add('tax-price');
    shippingPrice.classList.add('shipping-price');
    totalTitlePrice.classList.add('total-title-price');

    wrapper?.appendChild(main);
    main.appendChild(catalogElement);
    catalogElement.appendChild(sneakersImage);
    catalogElement.appendChild(sneakersName);
    catalogElement.appendChild(basketPriceWrapper);
    basketPriceWrapper.appendChild(whiteBasket);
    basketPriceWrapper.appendChild(price);
    aside?.appendChild(basket);
    basket.appendChild(title);
    basket.appendChild(basketElement);
    basketElement.appendChild(basketElementImage);
    basketElement.appendChild(basketItemInfoWrapper);
    basketItemInfoWrapper.appendChild(basketSneakersName);
    basketItemInfoWrapper.appendChild(plusWrapper);
    plusWrapper.appendChild(minus);
    plusWrapper.appendChild(quantity);
    plusWrapper.appendChild(plus);
    plusWrapper.appendChild(basketPrice);
    wrapper?.appendChild(aside);
    basketElement.appendChild(deleteBasketItem);
    aside.appendChild(promo);
    promo.appendChild(promoTitle);
    promo.appendChild(inputWrapper);
    inputWrapper.appendChild(promoInput);
    inputWrapper.appendChild(promoButton);
    aside.appendChild(total);
    total.appendChild(totalTitlesWrapper);
    totalTitlesWrapper.append(subtotal, tax, shipping, totalTitle);
    total.appendChild(totalPricesWrapper);
    totalPricesWrapper.append(subtotalPrice, taxPrice, shippingPrice, totalTitlePrice);
}

Element();